spring:
  config:
    import: secrets.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      platform: mysql
  main:
    banner-mode: off
logging:
  level:
    org.springframework: error
server:
  error:
    include-message: always
    include-stacktrace: never
  port: 35462