spring:
  config:
    import: secrets.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.SQLServerDialect
    database: sql_server
  sql:
    init:
      mode: always
  main:
    banner-mode: off
logging:
  level:
    org.springframework: error
server:
  error:
    include-message: always
    include-stacktrace: never