spring:
  datasource:
    url: jdbc:sqlserver://7.tcp.eu.ngrok.io:13913;encrypt=true;trustServerCertificate=true;databaseName=apendo_seat
    username: apendo
    password: Army-Donut-Pendant
notion:
  secret: 41fc9c3e356507dfa9314b378820da6bcb64716f1af6f4c45046775601700cb93527e68ea5402c1bc170c520e2edb6a41f0d987635c9885e29fc0aa5b14ef0d5
  aes_key: 8749ebe086da0466128aa8ed34b75032
  email: apendo.operations@outlook.com
  password: H4SZfC%cKnnKes4HQC7k$N2WNvb!bG9L%jfktiAPgUs6nDBB*^G4D@Ty*Te!C9S
  registerUrl: http://localhost:3000/auth/register
server:
  port: 35462