spring:
  datasource:
    url: jdbc:sqlserver://
    username: 
    password: 
  jpa:
    database: sql_server
notion:
  adminEmail: 
  adminFirstName: 
  adminLastName: 
  secret: 
  aes_key: 
  smtp_auth_email: 
  smtp_auth_password: 
  smtp_auth: true
  smtp_starttls_enable: true
  smtp_host: 
  smtp_port: 
  mail_from: 
  registerUrl: 
  resetPasswordUrl: 
  enableSwagger: true
  allowedCorsUrls:
    - 
server:
  port: 9000
